fix: use URL-safe base64 encoding
Prior to this commit, this used standard encoding, which worked up until
relatively recently. Now, unfortunately, using standard encoding appears
to be unsupported:

```
error: unexpected status code from GitHub API (401): {
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

This is, in a sense, not surprising because JWTs are typically base64
URL-safe encoded. It's surprising that this worked before, however.